# This Makefile builds the exiv2 library native client wrapper app.
# You have to build exiv2 with native client before. We published
# a patch for building exiv2 0.23 with naclports elsewhere.
# After `make` these files must be placed in bin/
#   photo_metadata_privacy_x86_32.nexe 
#   photo_metadata_privacy_x86_64.nexe
# They are already configured in
#   photo_metadata_privacy_x86_32.nexe photo_metadata_privacy_x86_64.msf


# Copyright (c) 2012 The Native Client Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# GNU Make based build file.  For details on GNU Make see:
#   http://www.gnu.org/software/make/manual/make.html

VALID_TOOLCHAINS := newlib glibc pnacl linux

NACL_SDK_ROOT ?= $(abspath $(CURDIR)/../../..)
include $(NACL_SDK_ROOT)/tools/common.mk

TARGET = photo_metadata_privacy
DEPS =
LIBS = $(DEPS) ppapi_cpp ppapi pthread exiv2 expat z jsoncpp

CFLAGS = -Wall
SOURCES = src/photo_metadata_privacy.cc \
          src/base64.cc \
          src/photo_metadata_privacy_downloader.cc

# Build rules generated by macros from common.mk:

$(foreach dep,$(DEPS),$(eval $(call DEPEND_RULE,$(dep))))
$(foreach src,$(SOURCES),$(eval $(call COMPILE_RULE,$(src),$(CFLAGS))))

ifeq ($(CONFIG),Release)
$(eval $(call LINK_RULE,$(TARGET)_unstripped,$(SOURCES),$(LIBS),$(DEPS)))
$(eval $(call STRIP_RULE,$(TARGET),$(TARGET)_unstripped))
else
$(eval $(call LINK_RULE,$(TARGET),$(SOURCES),$(LIBS),$(DEPS)))
endif

$(eval $(call NMF_RULE,$(TARGET),))



